### ISSUE TITLE
StrictVersion instance run error on launch

### ISSUE THREAD

**Issue by codereaver** [gaining/Resetter#68]
*Issue title
StrictVersion instance

*Linux Distro and version
18.04.1 LTS
python - Python 2.7.15rc1

*Version of Resetter
2.2.3

*Description of Issue
When trying to run application receiving following error: 
Traceback (most recent call last):
  File "/usr/lib/resetter/Resetter.py", line 567, in <module>
    window = UiMainWindow()
  File "/usr/lib/resetter/Resetter.py", line 30, in __init__
    self.d_env = Settings()
  File "/usr/lib/resetter/SetEnvironment.py", line 27, in __init__
    self.checkForUpdate()
  File "/usr/lib/resetter/SetEnvironment.py", line 123, in checkForUpdate
    if site_version > current_version:
  File "/usr/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'

*Content of log file located in /var/log/resetter/resetter.log if applicable

**Comment by gaining** [comment]
Related to #67
