### ISSUE TITLE
AttributeError: StrictVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by wingrez** [gaining/Resetter#71]
Traceback (most recent call last):
  File "/usr/lib/resetter/Resetter.py", line 514, in <module>
    window = UiMainWindow()
  File "/usr/lib/resetter/Resetter.py", line 28, in __init__
    self.d_env = Settings()
  File "/usr/lib/resetter/SetEnvironment.py", line 30, in __init__
    self.checkForUpdate()
  File "/usr/lib/resetter/SetEnvironment.py", line 201, in checkForUpdate
    if site_version > current_version:
  File "/usr/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'

**Comment by gaining** [comment]
https://github.com/gaining/Resetter/releases/latest
