### ISSUE TITLE
Get stuck at 5%

### ISSUE THREAD

**Issue by caliman** [gaining/Resetter#8]
Have waited for over one hour and it is still only at 5%. Still on Loading packages.

Have selected to reset all packages but keep my user. Using Ubuntu 16.10

**Comment by gaining** [comment]
can you send me the content of your /var/log/resetter/resetter.log ?

**Comment by gaining** [comment]
If someone else is having the same issue at @caliman, can they post their log file here? I'm unable to reproduce this on my 16.10 vm.

**Comment by caliman** [comment]
I now tried installing 17.04 and then run the resetter but it is still the same. My resetter.log:
2017-04-15 10:48:07,682 - __main__ - __init__ - DEBUG - program was called via sudo or gksu
2017-04-15 10:48:07,700 - __main__ - detectOS - INFO - OS is Ubuntu 17.04
2017-04-15 10:48:13,060 - __main__ - getInstalledList - INFO - getting installed list...
2017-04-15 10:48:13,108 - __main__ - getInstalledList - DEBUG - installed list was generated with 2802 apps installed
2017-04-15 10:48:13,108 - __main__ - processManifest - INFO - processing updated manifest...
2017-04-15 10:48:13,110 - __main__ - processManifest - INFO - manifest processing complete
2017-04-15 10:48:13,110 - __main__ - compareFiles - INFO - comparing updated manifest and installed list...
2017-04-15 10:48:13,983 - __main__ - compareFiles - INFO - CompareFiles() Completed
2017-04-15 10:48:13,983 - __main__ - getMissingPackages - INFO - generating install list
2017-04-15 10:48:15,179 - __main__ - getMissingPackages - INFO - getmissingPackages() Completed
2017-04-15 10:48:15,179 - __main__ - getLocalUserList - INFO - getting local users...
2017-04-15 10:48:15,184 - __main__ - getLocalUserList - INFO - getLocalUserList() completed
2017-04-15 10:48:15,184 - __main__ - getOldKernels - INFO - getting old kernels...
2017-04-15 10:48:15,224 - __main__ - getOldKernels - INFO - getOldKernels() completed
2017-04-15 10:48:34,361 - Account - custom_user - INFO - Custom user creation complete

I then run resetter from my terminal and it seems like I have some issues with packages because it failed  with:

default
is marked for Delete User and Home
Adding custom user
Traceback (most recent call last):
  File "/usr/lib/resetter/CustomApplyDialog.py", line 55, in run
    self.pkg.mark_delete(True, True)
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 1285, in mark_delete
    fix.resolve()
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by gaining** [comment]
Thanks. I'll get to it.

**Comment by gaining** [comment]
@caliman try to run `sudo apt install -f` then run resetter again to see if the program runs ok after. Seems like you have broken packages prior to running it.

**Comment by caliman** [comment]
Tried it but didn't help. Tried only some packages at a time and it worked and could also install all new packages. Then ran it again and selected some others and it stopped. Seems like it stops on some packages but not on others. Now went on with reinstalling from image. Thanks anyway and maybe close this issue if it was only me with broken packages. Maybe for you to add some error info instead of just spinning like it is still working.

**Comment by gaining** [comment]
I added a workaround on the program so that it will skip packages that the resolver was unable to fix before removing for now. Also a prompt will be shown at the end on which packages were skipped if this happened.  Done in 3090815
